import type {Metadata} from 'next'
import {Inter, Montserrat} from 'next/font/google'
import './globals.css'
import React from "react";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({subsets: ['latin'], variable: '--font-inter'})
const montserrat = Montserrat({subsets: ['latin'], variable: '--font-montserrat'})

export const metadata: Metadata = {
    title: 'My Diary | Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={`${inter.variable} ${montserrat.variable} flex flex-col  mt-10 bg-neutral-900`}>
        <div className={'items-center  m-auto'}>
            <Link href={'/'}>
                <Image src={'/images/logo.png'} width={200} height={200} alt={'My diary'}/>
            </Link>
        </div>
        <div>
            {children}
        </div>
       </body>
        </html>
    )
}
